### ISSUE TITLE
Usar imagem genérica de fundo *7

### ISSUE THREAD

**Issue by julianaomi** [C-K-R-S/Killer-Run#10]
Usar uma imagem da Internet, sem restrição de direitos autorais, para usar no desenvolvimento do jogo. Não precisa, logo, ser a imagem final do jogo, mas apenas uma mais genérica para auxiliar no processo.

Se o jogo não tiver imagem, mas apenas texto, basta a cor, portanto.

**Comment by WBluan** [comment]
mapa - https://opengameart.org/content/lpc-tile-atlas

**Comment by moniqpj** [comment]
esse é legal também - https://opengameart.org/content/cave-tileset-0
