### ISSUE TITLE
Definir e projetar tela de encerramento *17

### ISSUE THREAD

**Issue by julianaomi** [C-K-R-S/Killer-Run#20]
Assim como a tela de abertura (#16), a tela de encerramento ajudará, durante o jogo, a (re)carregar os objetos das cenas, zerar placar, entre outros. São, pois, também duas subtarefas:

Definir a tela de encerramento;
Programar a tela de encerramento.
Depende de #15, e recomenda-se fazer depois de #16.

**Comment by saraazimmer** [comment]
Tela de encerramento concluída, esta no repositório na pasta "julinha".
