### ISSUE TITLE
Definir hospedagem do servidor do jogo 

### ISSUE THREAD

**Issue by julianaomi** [C-K-R-S/Killer-Run#31]
Definir forma e local de hospedagem do servidor de jogo para que os clientes possam de conectar. Impactado por

**Comment by saraazimmer** [comment]
Vai ser utilizado no Google.
Obs: Adicionar no código futuramente.

**Comment by saraazimmer** [comment]
Hospedagem: 
Estático é GitHub pages
Dinâmico é Heroku
