### ISSUE TITLE
Definir a base conceitual do jogo

### ISSUE THREAD

**Issue by julianaomi** [C-K-R-S/Killer-Run#4]
Passo a passo do que irá acontecer:
Referências: literatura, mídias em geral e outros jogos
 Roteiro: início, meio e fim
 Personagens: perfis, evolução
 Artefatos: armas, poções etc.
 Mundo/universo

**Comment by moniqpj** [comment]
Personagem, irá evoluir?
Os objetos vão ficar de que forma?
Mundo ou universo, época e conceito

**Comment by moniqpj** [comment]
Passo a passo do que irá acontecer: Cada personagem irá surgir em um ponto do mapa, a sobrevivente deixa um rastro que some após alguns segundos enquanto a mesma procura uma faca para se defender do assassino. Se a sobrevivente acha a faca antes do assassino a encontrar, precisa matar o assassino com a faca. Desde o inicio do jogo o chat por voz já estará ativo para que o assassino e a sobrevivente tenham chance de se falar durante o jogo.
Referências: pânico (filme), dead by daylight (jogo), darkwood (jogo), lavender town (música aterrorizante do jogo pokemon)
Roteiro: início, meio e fim
Personagens: -Killer, baseado no ghostface do filme Pânico, tem objetivo de matar a sobrevivente. -Survivor, baseada na Sidney também do filme Pânico, que precisa fugir do assassino e achar uma faca para poder matá-lo.
Artefatos: Faca e lanterna (ponto de luz no personagem)
Mundo/universo: Floresta com arvores e pedras de noite, em um ano que não se tinha celulares para pedir socorro.
