### ISSUE TITLE
Estudar sobre design de jogos digitais

### ISSUE THREAD

**Issue by moniqpj** [C-K-R-S/Killer-Run#8]
Sugestões:

[Game Maker's Toolkit](https://www.youtube.com/user/McBacon1337) (canal do Youtube)
[Game Developer](https://www.gamedeveloper.com/)

**Comment by julianaomi** [comment]
y:0 na gravidade para fazer um tabuleiro/labirinto. Part 4.html

**Comment by julianaomi** [comment]
https://terser.itch.io/dark-demise esse grafico/cenario
https://opengameart.org/content/rigged-suicide-girl-body personagem do fim do jogo, caso o sobrevivente morra

**Comment by julianaomi** [comment]
https://github.com/boidacarapreta/catalogo-de-jogos AQUI TÊM OS JOGOS
